import { Flashcard } from '../types/flashcardTypes';

export const sampleFlashcards: Flashcard[] = [
  {
    id: '1',
    englishWord: 'beautiful',
    vietnameseTranslation: 'đẹp',
    partOfSpeech: 'adjective',
    phoneticTranscription: '/ˈbjuːtɪfl/',
    exampleSentence: 'The sunset is beautiful tonight.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'general',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '2',
    englishWord: 'restaurant',
    vietnameseTranslation: 'nhà hàng',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈrestərɑːnt/',
    exampleSentence: 'We had dinner at a nice restaurant.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'food',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '3',
    englishWord: 'accomplish',
    vietnameseTranslation: 'hoàn thành',
    partOfSpeech: 'verb',
    phoneticTranscription: '/əˈkʌmplɪʃ/',
    exampleSentence: 'She worked hard to accomplish her goals.',
    difficulty: 'intermediate',
    isLearned: false,
    starRating: 0,
    topicId: 'general',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '4',
    englishWord: 'happy',
    vietnameseTranslation: 'vui vẻ',
    partOfSpeech: 'adjective',
    phoneticTranscription: '/ˈhæpi/',
    exampleSentence: 'She felt happy after receiving good news.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'general',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '5',
    englishWord: 'book',
    vietnameseTranslation: 'sách',
    partOfSpeech: 'noun',
    phoneticTranscription: '/bʊk/',
    exampleSentence: 'I read a great book yesterday.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'general',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '6',
    englishWord: 'run',
    vietnameseTranslation: 'chạy',
    partOfSpeech: 'verb',
    phoneticTranscription: '/rʌn/',
    exampleSentence: 'He likes to run in the park every morning.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'general',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '7',
    englishWord: 'delicious',
    vietnameseTranslation: 'ngon',
    partOfSpeech: 'adjective',
    phoneticTranscription: '/dɪˈlɪʃəs/',
    exampleSentence: 'The food at this restaurant is delicious.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'food',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '8',
    englishWord: 'computer',
    vietnameseTranslation: 'máy tính',
    partOfSpeech: 'noun',
    phoneticTranscription: '/kəmˈpjuːtər/',
    exampleSentence: 'She bought a new computer for work.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'technology',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '9',
    englishWord: 'travel',
    vietnameseTranslation: 'du lịch',
    partOfSpeech: 'verb',
    phoneticTranscription: '/ˈtrævl/',
    exampleSentence: 'They love to travel to new countries.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'travel',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '10',
    englishWord: 'meeting',
    vietnameseTranslation: 'cuộc họp',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈmiːtɪŋ/',
    exampleSentence: 'We have a meeting at 3 PM today.',
    difficulty: 'intermediate',
    isLearned: false,
    starRating: 0,
    topicId: 'business',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '11',
    englishWord: 'healthy',
    vietnameseTranslation: 'khỏe mạnh',
    partOfSpeech: 'adjective',
    phoneticTranscription: '/ˈhelθi/',
    exampleSentence: 'Eating vegetables is good for staying healthy.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'health',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '12',
    englishWord: 'friend',
    vietnameseTranslation: 'bạn bè',
    partOfSpeech: 'noun',
    phoneticTranscription: '/frend/',
    exampleSentence: 'She is my best friend.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'general',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '13',
    englishWord: 'learn',
    vietnameseTranslation: 'học',
    partOfSpeech: 'verb',
    phoneticTranscription: '/lɜːrn/',
    exampleSentence: 'I want to learn a new language.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'general',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '14',
    englishWord: 'coffee',
    vietnameseTranslation: 'cà phê',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈkɔːfi/',
    exampleSentence: 'I drink coffee every morning.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'food',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '15',
    englishWord: 'internet',
    vietnameseTranslation: 'mạng internet',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈɪntərnet/',
    exampleSentence: 'The internet is very slow today.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'technology',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '16',
    englishWord: 'hotel',
    vietnameseTranslation: 'khách sạn',
    partOfSpeech: 'noun',
    phoneticTranscription: '/hoʊˈtel/',
    exampleSentence: 'We stayed at a comfortable hotel.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'travel',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '17',
    englishWord: 'project',
    vietnameseTranslation: 'dự án',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈprɑːdʒekt/',
    exampleSentence: 'The team is working on a new project.',
    difficulty: 'intermediate',
    isLearned: false,
    starRating: 0,
    topicId: 'business',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '18',
    englishWord: 'doctor',
    vietnameseTranslation: 'bác sĩ',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈdɑːktər/',
    exampleSentence: 'You should see a doctor if you feel sick.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'health',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '19',
    englishWord: 'difficult',
    vietnameseTranslation: 'khó khăn',
    partOfSpeech: 'adjective',
    phoneticTranscription: '/ˈdɪfɪkəlt/',
    exampleSentence: 'This puzzle is very difficult to solve.',
    difficulty: 'intermediate',
    isLearned: false,
    starRating: 0,
    topicId: 'general',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '20',
    englishWord: 'kitchen',
    vietnameseTranslation: 'nhà bếp',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈkɪtʃɪn/',
    exampleSentence: 'She is cooking in the kitchen.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'food',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '21',
    englishWord: 'software',
    vietnameseTranslation: 'phần mềm',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈsɔːftwer/',
    exampleSentence: 'This software is easy to use.',
    difficulty: 'intermediate',
    isLearned: false,
    starRating: 0,
    topicId: 'technology',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '22',
    englishWord: 'airplane',
    vietnameseTranslation: 'máy bay',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈerpleɪn/',
    exampleSentence: 'The airplane takes off at 7 PM.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'travel',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '23',
    englishWord: 'manager',
    vietnameseTranslation: 'quản lý',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈmænɪdʒər/',
    exampleSentence: 'The manager approved the budget.',
    difficulty: 'intermediate',
    isLearned: false,
    starRating: 0,
    topicId: 'business',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '24',
    englishWord: 'medicine',
    vietnameseTranslation: 'thuốc',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈmedɪsn/',
    exampleSentence: 'Take this medicine twice a day.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'health',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '25',
    englishWord: 'family',
    vietnameseTranslation: 'gia đình',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈfæməli/',
    exampleSentence: 'My family lives in Hanoi.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'general',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '26',
    englishWord: 'eat',
    vietnameseTranslation: 'ăn',
    partOfSpeech: 'verb',
    phoneticTranscription: '/iːt/',
    exampleSentence: 'I eat breakfast every morning.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'food',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '27',
    englishWord: 'website',
    vietnameseTranslation: 'trang web',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈwebsaɪt/',
    exampleSentence: 'I found this information on a website.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'technology',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '28',
    englishWord: 'passport',
    vietnameseTranslation: 'hộ chiếu',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈpæspɔːrt/',
    exampleSentence: 'Don’t forget to bring your passport.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'travel',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '29',
    englishWord: 'contract',
    vietnameseTranslation: 'hợp đồng',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈkɑːntrækt/',
    exampleSentence: 'They signed a contract yesterday.',
    difficulty: 'intermediate',
    isLearned: false,
    starRating: 0,
    topicId: 'business',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '30',
    englishWord: 'hospital',
    vietnameseTranslation: 'bệnh viện',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈhɑːspɪtl/',
    exampleSentence: 'He was taken to the hospital.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'health',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '31',
    englishWord: 'big',
    vietnameseTranslation: 'lớn',
    partOfSpeech: 'adjective',
    phoneticTranscription: '/bɪɡ/',
    exampleSentence: 'They live in a big house.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'general',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '32',
    englishWord: 'cook',
    vietnameseTranslation: 'nấu ăn',
    partOfSpeech: 'verb',
    phoneticTranscription: '/kʊk/',
    exampleSentence: 'She loves to cook traditional Vietnamese food.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'food',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '33',
    englishWord: 'smartphone',
    vietnameseTranslation: 'điện thoại thông minh',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈsmɑːrtfoʊn/',
    exampleSentence: 'I got a new smartphone yesterday.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'technology',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '34',
    englishWord: 'ticket',
    vietnameseTranslation: 'vé',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈtɪkɪt/',
    exampleSentence: 'I bought a ticket for the train.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'travel',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '35',
    englishWord: 'employee',
    vietnameseTranslation: 'nhân viên',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ɪmˈplɔɪiː/',
    exampleSentence: 'The employee received a promotion.',
    difficulty: 'intermediate',
    isLearned: false,
    starRating: 0,
    topicId: 'business',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '36',
    englishWord: 'pain',
    vietnameseTranslation: 'đau',
    partOfSpeech: 'noun',
    phoneticTranscription: '/peɪn/',
    exampleSentence: 'He has a pain in his back.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'health',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '37',
    englishWord: 'small',
    vietnameseTranslation: 'nhỏ',
    partOfSpeech: 'adjective',
    phoneticTranscription: '/smɔːl/',
    exampleSentence: 'This is a small room.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'general',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '38',
    englishWord: 'bread',
    vietnameseTranslation: 'bánh mì',
    partOfSpeech: 'noun',
    phoneticTranscription: '/bred/',
    exampleSentence: 'I bought some fresh bread.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'food',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '39',
    englishWord: 'laptop',
    vietnameseTranslation: 'máy tính xách tay',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈlæptɑːp/',
    exampleSentence: 'I work on my laptop every day.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'technology',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '40',
    englishWord: 'tourist',
    vietnameseTranslation: 'khách du lịch',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈtʊrɪst/',
    exampleSentence: 'Many tourists visit this city.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'travel',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '41',
    englishWord: 'business',
    vietnameseTranslation: 'kinh doanh',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈbɪznəs/',
    exampleSentence: 'She started her own business.',
    difficulty: 'intermediate',
    isLearned: false,
    starRating: 0,
    topicId: 'business',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '42',
    englishWord: 'fever',
    vietnameseTranslation: 'sốt',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈfiːvər/',
    exampleSentence: 'He has a high fever.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'health',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '43',
    englishWord: 'fast',
    vietnameseTranslation: 'nhanh',
    partOfSpeech: 'adjective',
    phoneticTranscription: '/fæst/',
    exampleSentence: 'This car is very fast.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'general',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '44',
    englishWord: 'soup',
    vietnameseTranslation: 'súp',
    partOfSpeech: 'noun',
    phoneticTranscription: '/suːp/',
    exampleSentence: 'I love eating hot soup in winter.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'food',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '45',
    englishWord: 'download',
    vietnameseTranslation: 'tải xuống',
    partOfSpeech: 'verb',
    phoneticTranscription: '/ˈdaʊnloʊd/',
    exampleSentence: 'You can download the app from the store.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'technology',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '46',
    englishWord: 'luggage',
    vietnameseTranslation: 'hành lý',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈlʌɡɪdʒ/',
    exampleSentence: 'I lost my luggage at the airport.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'travel',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '47',
    englishWord: 'salary',
    vietnameseTranslation: 'lương',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈsæləri/',
    exampleSentence: 'Her salary increased this year.',
    difficulty: 'intermediate',
    isLearned: false,
    starRating: 0,
    topicId: 'business',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '48',
    englishWord: 'injury',
    vietnameseTranslation: 'chấn thương',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈɪndʒəri/',
    exampleSentence: 'He suffered an injury during the game.',
    difficulty: 'intermediate',
    isLearned: false,
    starRating: 0,
    topicId: 'health',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '49',
    englishWord: 'good',
    vietnameseTranslation: 'tốt',
    partOfSpeech: 'adjective',
    phoneticTranscription: '/ɡʊd/',
    exampleSentence: 'This is a good book.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'general',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '50',
    englishWord: 'dinner',
    vietnameseTranslation: 'bữa tối',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈdɪnər/',
    exampleSentence: 'We had dinner at 7 PM.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'food',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '51',
    englishWord: 'application',
    vietnameseTranslation: 'ứng dụng',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˌæplɪˈkeɪʃn/',
    exampleSentence: 'This application is very useful.',
    difficulty: 'intermediate',
    isLearned: false,
    starRating: 0,
    topicId: 'technology',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '52',
    englishWord: 'vacation',
    vietnameseTranslation: 'kỳ nghỉ',
    partOfSpeech: 'noun',
    phoneticTranscription: '/veɪˈkeɪʃn/',
    exampleSentence: 'We’re going on vacation next week.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'travel',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '53',
    englishWord: 'office',
    vietnameseTranslation: 'văn phòng',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈɔːfɪs/',
    exampleSentence: 'She works in an office downtown.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'business',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '54',
    englishWord: 'exercise',
    vietnameseTranslation: 'tập thể dục',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈeksərsaɪz/',
    exampleSentence: 'Exercise is important for health.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'health',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '55',
    englishWord: 'old',
    vietnameseTranslation: 'già',
    partOfSpeech: 'adjective',
    phoneticTranscription: '/oʊld/',
    exampleSentence: 'This is an old house.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'general',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '56',
    englishWord: 'rice',
    vietnameseTranslation: 'gạo',
    partOfSpeech: 'noun',
    phoneticTranscription: '/raɪs/',
    exampleSentence: 'Rice is a staple food in Vietnam.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'food',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '57',
    englishWord: 'password',
    vietnameseTranslation: 'mật khẩu',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈpæswɜːrd/',
    exampleSentence: 'Don’t share your password with anyone.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'technology',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '58',
    englishWord: 'map',
    vietnameseTranslation: 'bản đồ',
    partOfSpeech: 'noun',
    phoneticTranscription: '/mæp/',
    exampleSentence: 'I used a map to find the hotel.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'travel',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '59',
    englishWord: 'client',
    vietnameseTranslation: 'khách hàng',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈklaɪənt/',
    exampleSentence: 'The client was happy with the service.',
    difficulty: 'intermediate',
    isLearned: false,
    starRating: 0,
    topicId: 'business',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '60',
    englishWord: 'surgery',
    vietnameseTranslation: 'phẫu thuật',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈsɜːrdʒəri/',
    exampleSentence: 'He needs surgery on his knee.',
    difficulty: 'intermediate',
    isLearned: false,
    starRating: 0,
    topicId: 'health',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '61',
    englishWord: 'new',
    vietnameseTranslation: 'mới',
    partOfSpeech: 'adjective',
    phoneticTranscription: '/njuː/',
    exampleSentence: 'I bought a new phone.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'general',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '62',
    englishWord: 'fruit',
    vietnameseTranslation: 'trái cây',
    partOfSpeech: 'noun',
    phoneticTranscription: '/fruːt/',
    exampleSentence: 'I eat fruit every day.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'food',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '63',
    englishWord: 'email',
    vietnameseTranslation: 'thư điện tử',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈiːmeɪl/',
    exampleSentence: 'I sent you an email yesterday.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'technology',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '64',
    englishWord: 'guide',
    vietnameseTranslation: 'hướng dẫn viên',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ɡaɪd/',
    exampleSentence: 'The guide showed us around the city.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'travel',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '65',
    englishWord: 'company',
    vietnameseTranslation: 'công ty',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈkʌmpəni/',
    exampleSentence: 'She works for a big company.',
    difficulty: 'intermediate',
    isLearned: false,
    starRating: 0,
    topicId: 'business',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '66',
    englishWord: 'nurse',
    vietnameseTranslation: 'y tá',
    partOfSpeech: 'noun',
    phoneticTranscription: '/nɜːrs/',
    exampleSentence: 'The nurse took my temperature.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'health',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '67',
    englishWord: 'young',
    vietnameseTranslation: 'trẻ',
    partOfSpeech: 'adjective',
    phoneticTranscription: '/jʌŋ/',
    exampleSentence: 'She is a young student.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'general',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '68',
    englishWord: 'vegetable',
    vietnameseTranslation: 'rau củ',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈvedʒtəbl/',
    exampleSentence: 'Eat more vegetables for better health.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'food',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '69',
    englishWord: 'program',
    vietnameseTranslation: 'chương trình',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈproʊɡræm/',
    exampleSentence: 'I’m writing a computer program.',
    difficulty: 'intermediate',
    isLearned: false,
    starRating: 0,
    topicId: 'technology',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '70',
    englishWord: 'beach',
    vietnameseTranslation: 'bãi biển',
    partOfSpeech: 'noun',
    phoneticTranscription: '/biːtʃ/',
    exampleSentence: 'We’re going to the beach this weekend.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'travel',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '71',
    englishWord: 'market',
    vietnameseTranslation: 'thị trường',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈmɑːrkɪt/',
    exampleSentence: 'The company entered a new market.',
    difficulty: 'intermediate',
    isLearned: false,
    starRating: 0,
    topicId: 'business',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '72',
    englishWord: 'vitamin',
    vietnameseTranslation: 'vitamin',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈvaɪtəmɪn/',
    exampleSentence: 'Vitamins are good for your health.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'health',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '73',
    englishWord: 'important',
    vietnameseTranslation: 'quan trọng',
    partOfSpeech: 'adjective',
    phoneticTranscription: '/ɪmˈpɔːrtnt/',
    exampleSentence: 'This is an important meeting.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'general',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '74',
    englishWord: 'cake',
    vietnameseTranslation: 'bánh ngọt',
    partOfSpeech: 'noun',
    phoneticTranscription: '/keɪk/',
    exampleSentence: 'I baked a chocolate cake.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'food',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '75',
    englishWord: 'network',
    vietnameseTranslation: 'mạng lưới',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈnetwɜːrk/',
    exampleSentence: 'Our network is down today.',
    difficulty: 'intermediate',
    isLearned: false,
    starRating: 0,
    topicId: 'technology',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '76',
    englishWord: 'culture',
    vietnameseTranslation: 'văn hóa',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈkʌltʃər/',
    exampleSentence: 'I love learning about different cultures.',
    difficulty: 'intermediate',
    isLearned: false,
    starRating: 0,
    topicId: 'travel',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '77',
    englishWord: 'profit',
    vietnameseTranslation: 'lợi nhuận',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈprɑːfɪt/',
    exampleSentence: 'The company made a huge profit.',
    difficulty: 'intermediate',
    isLearned: false,
    starRating: 0,
    topicId: 'business',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '78',
    englishWord: 'sleep',
    vietnameseTranslation: 'ngủ',
    partOfSpeech: 'verb',
    phoneticTranscription: '/sliːp/',
    exampleSentence: 'I need to sleep early tonight.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'health',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '79',
    englishWord: 'easy',
    vietnameseTranslation: 'dễ dàng',
    partOfSpeech: 'adjective',
    phoneticTranscription: '/ˈiːzi/',
    exampleSentence: 'This task is easy to complete.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'general',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '80',
    englishWord: 'meat',
    vietnameseTranslation: 'thịt',
    partOfSpeech: 'noun',
    phoneticTranscription: '/miːt/',
    exampleSentence: 'We grilled some meat for dinner.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'food',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '81',
    englishWord: 'data',
    vietnameseTranslation: 'dữ liệu',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈdeɪtə/',
    exampleSentence: 'We need to analyze the data.',
    difficulty: 'intermediate',
    isLearned: false,
    starRating: 0,
    topicId: 'technology',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '82',
    englishWord: 'museum',
    vietnameseTranslation: 'bảo tàng',
    partOfSpeech: 'noun',
    phoneticTranscription: '/mjuˈziːəm/',
    exampleSentence: 'We visited a history museum.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'travel',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '83',
    englishWord: 'advertisement',
    vietnameseTranslation: 'quảng cáo',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˌædvərˈtaɪzmənt/',
    exampleSentence: 'I saw an advertisement on TV.',
    difficulty: 'intermediate',
    isLearned: false,
    starRating: 0,
    topicId: 'business',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '84',
    englishWord: 'stress',
    vietnameseTranslation: 'căng thẳng',
    partOfSpeech: 'noun',
    phoneticTranscription: '/stres/',
    exampleSentence: 'Work can cause a lot of stress.',
    difficulty: 'intermediate',
    isLearned: false,
    starRating: 0,
    topicId: 'health',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '85',
    englishWord: 'hot',
    vietnameseTranslation: 'nóng',
    partOfSpeech: 'adjective',
    phoneticTranscription: '/hɑːt/',
    exampleSentence: 'The weather is hot today.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'general',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '86',
    englishWord: 'drink',
    vietnameseTranslation: 'uống',
    partOfSpeech: 'verb',
    phoneticTranscription: '/drɪŋk/',
    exampleSentence: 'I drink water every day.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'food',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '87',
    englishWord: 'update',
    vietnameseTranslation: 'cập nhật',
    partOfSpeech: 'verb',
    phoneticTranscription: '/ˌʌpˈdeɪt/',
    exampleSentence: 'I need to update my software.',
    difficulty: 'intermediate',
    isLearned: false,
    starRating: 0,
    topicId: 'technology',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '88',
    englishWord: 'city',
    vietnameseTranslation: 'thành phố',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈsɪti/',
    exampleSentence: 'Hanoi is a beautiful city.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'travel',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '89',
    englishWord: 'budget',
    vietnameseTranslation: 'ngân sách',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈbʌdʒɪt/',
    exampleSentence: 'We need to plan our budget carefully.',
    difficulty: 'intermediate',
    isLearned: false,
    starRating: 0,
    topicId: 'business',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '90',
    englishWord: 'diet',
    vietnameseTranslation: 'chế độ ăn uống',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈdaɪət/',
    exampleSentence: 'She follows a healthy diet.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'health',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '91',
    englishWord: 'cold',
    vietnameseTranslation: 'lạnh',
    partOfSpeech: 'adjective',
    phoneticTranscription: '/koʊld/',
    exampleSentence: 'It’s cold outside today.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'general',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '92',
    englishWord: 'breakfast',
    vietnameseTranslation: 'bữa sáng',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈbrekfəst/',
    exampleSentence: 'I had eggs for breakfast.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'food',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '93',
    englishWord: 'online',
    vietnameseTranslation: 'trực tuyến',
    partOfSpeech: 'adjective',
    phoneticTranscription: '/ˈɑːnlaɪn/',
    exampleSentence: 'I shop online for convenience.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'technology',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '94',
    englishWord: 'train',
    vietnameseTranslation: 'tàu hỏa',
    partOfSpeech: 'noun',
    phoneticTranscription: '/treɪn/',
    exampleSentence: 'I took the train to work.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'travel',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '95',
    englishWord: 'presentation',
    vietnameseTranslation: 'bài thuyết trình',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˌpreznˈteɪʃn/',
    exampleSentence: 'She gave a great presentation.',
    difficulty: 'intermediate',
    isLearned: false,
    starRating: 0,
    topicId: 'business',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '96',
    englishWord: 'temperature',
    vietnameseTranslation: 'nhiệt độ',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈtemprətʃər/',
    exampleSentence: 'The temperature is 30°C today.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'health',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '97',
    englishWord: 'nice',
    vietnameseTranslation: 'đẹp, tốt',
    partOfSpeech: 'adjective',
    phoneticTranscription: '/naɪs/',
    exampleSentence: 'This is a nice place to visit.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'general',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '98',
    englishWord: 'lunch',
    vietnameseTranslation: 'bữa trưa',
    partOfSpeech: 'noun',
    phoneticTranscription: '/lʌntʃ/',
    exampleSentence: 'Let’s have lunch together.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'food',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '99',
    englishWord: 'device',
    vietnameseTranslation: 'thiết bị',
    partOfSpeech: 'noun',
    phoneticTranscription: '/dɪˈvaɪs/',
    exampleSentence: 'This device is very advanced.',
    difficulty: 'intermediate',
    isLearned: false,
    starRating: 0,
    topicId: 'technology',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '100',
    englishWord: 'adventure',
    vietnameseTranslation: 'cuộc phiêu lưu',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ədˈventʃər/',
    exampleSentence: 'Traveling is a great adventure.',
    difficulty: 'intermediate',
    isLearned: false,
    starRating: 0,
    topicId: 'travel',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '101',
    englishWord: 'strategy',
    vietnameseTranslation: 'chiến lược',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈstrætədʒi/',
    exampleSentence: 'We need a new business strategy.',
    difficulty: 'intermediate',
    isLearned: false,
    starRating: 0,
    topicId: 'business',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '102',
    englishWord: 'energy',
    vietnameseTranslation: 'năng lượng',
    partOfSpeech: 'noun',
    phoneticTranscription: '/ˈenərdʒi/',
    exampleSentence: 'I don’t have much energy today.',
    difficulty: 'intermediate',
    isLearned: false,
    starRating: 0,
    topicId: 'health',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
  {
    id: '103',
    englishWord: 'kind',
    vietnameseTranslation: 'tử tế',
    partOfSpeech: 'adjective',
    phoneticTranscription: '/kaɪnd/',
    exampleSentence: 'He is a kind person.',
    difficulty: 'beginner',
    isLearned: false,
    starRating: 0,
    topicId: 'general',
    createdAt: new Date(),
    reviewCount: 0,
    easeFactor: 2.5,
    nextReviewDate: new Date(),
  },
];
